apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frank2kube.fullname" . }}-context-config
  labels:
    {{- include "frank2kube.labels" . | nindent 4 }}
data:
  context.xml: {{ .Files.Get "files/context.xml" | quote }}
immutable: true